In [1]:
import pandas as pd
import numpy as np

In [2]:
flights = pd.read_csv("../data/Extracted/Flights/nycflights13.csv")
flights.shape
flights.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0

In [3]:
flights.query("month == 1 & day == 1")
flights[(flights.month == 1) & (flights.day == 1)]

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
5,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0
6,2013,1,1,555.0,-5.0,913.0,19.0,B6,N516JB,507,EWR,FLL,158.0,1065,5.0,55.0
7,2013,1,1,557.0,-3.0,709.0,-14.0,EV,N829AS,5708,LGA,IAD,53.0,229,5.0,57.0
8,2013,1,1,557.0,-3.0,838.0,-8.0,B6,N593JB,79,JFK,MCO,140.0,944,5.0,57.0
9,2013,1,1,558.0,-2.0,753.0,8.0,AA,N3ALAA,301,LGA,ORD,138.0,733,5.0,58.0
10,2013,1,1,558.0,-2.0,849.0,-2.0,B6,N793JB,49,JFK,PBI,149.0,1028,5.0,58.0
11,2013,1,1,558.0,-2.0,853.0,-3.0,B6,N657JB,71,JFK,TPA,158.0,1005,5.0,58.0
12,2013,1,1,558.0,-2.0,924.0,7.0,UA,N29129,194,JFK,LAX,345.0,2475,5.0,58.0
13,2013,1,1,558.0,-2.0,923.0,-14.0,UA,N53441,1124,EWR,SFO,361.0,2565,5.0,58.0
14,2013,1,1,559.0,-1.0,941.0,31.0,AA,N3DUAA,707,LGA,DFW,257.0,1389,5.0,59.0
15,2013,1,1,559.0,0.0,702.0,-4.0,B6,N708JB,1806,JFK,BOS,44.0,187,5.0,59.0
16,2013,1,1,559.0,-1.0,854.0,-8.0,UA,N76515,1187,EWR,LAS,337.0,2227,5.0,59.0
17,2013,1,1,600.0,0.0,851.0,-7.0,B6,N595JB,371,LGA,FLL,152.0,1076,6.0,0.0
18,2013,1,1,600.0,0.0,837.0,12.0,MQ,N542MQ,4650,LGA,ATL,134.0,762,6.0,0.0
19,2013,1,1,601.0,1.0,844.0,-6.0,B6,N644JB,343,EWR,PBI,147.0,1023,6.0,1.0
20,2013,1,1,602.0,-8.0,812.0,-8.0,DL,N971DL,1919,LGA,MSP,170.0,1020,6.0,2.0
21,2013,1,1,602.0,-3.0,821.0,16.0,MQ,N730MQ,4401,LGA,DTW,105.0,502,6.0,2.0
22,2013,1,1,606.0,-4.0,858.0,-12.0,AA,N633AA,1895,EWR,MIA,152.0,1085,6.0,6.0
23,2013,1,1,606.0,-4.0,837.0,-8.0,DL,N3739P,1743,JFK,ATL,128.0,760,6.0,6.0
24,2013,1,1,607.0,0.0,858.0,-17.0,UA,N53442,1077,EWR,MIA,157.0,1085,6.0,7.0
25,2013,1,1,608.0,8.0,807.0,32.0,MQ,N9EAMQ,3768,EWR,ORD,139.0,719,6.0,8.0
26,2013,1,1,611.0,11.0,945.0,14.0,UA,N532UA,303,JFK,SFO,366.0,2586,6.0,11.0
27,2013,1,1,613.0,3.0,925.0,4.0,B6,N635JB,135,JFK,RSW,175.0,1074,6.0,13.0
28,2013,1,1,615.0,0.0,1039.0,-21.0,B6,N794JB,709,JFK,SJU,182.0,1598,6.0,15.0
29,2013,1,1,615.0,0.0,833.0,-9.0,DL,N326NB,575,EWR,ATL,120.0,746,6.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,2013,1,1,2140.0,5.0,210.0,-14.0,B6,N284JB,701,JFK,SJU,189.0,1598,21.0,40.0
813,2013,1,1,2157.0,2.0,43.0,2.0,B6,N537JB,43,JFK,MCO,140.0,944,21.0,57.0
814,2013,1,1,2158.0,-2.0,2254.0,-13.0,EV,N14998,4103,EWR,BWI,36.0,169,21.0,58.0
815,2013,1,1,2205.0,285.0,46.0,246.0,AA,N5DNAA,1999,EWR,MIA,146.0,1085,22.0,5.0
816,2013,1,1,2209.0,24.0,58.0,21.0,B6,N608JB,35,JFK,PBI,143.0,1028,22.0,9.0
817,2013,1,1,2209.0,14.0,2400.0,23.0,B6,N216JB,1109,JFK,RDU,86.0,427,22.0,9.0
818,2013,1,1,2211.0,26.0,2339.0,28.0,B6,N228JB,104,JFK,BUF,64.0,301,22.0,11.0
819,2013,1,1,2217.0,-12.0,249.0,-26.0,B6,N547JB,713,JFK,SJU,191.0,1598,22.0,17.0
820,2013,1,1,2217.0,47.0,140.0,73.0,B6,N516JB,21,JFK,TPA,163.0,1005,22.0,17.0
821,2013,1,1,2221.0,141.0,2331.0,127.0,EV,N13566,4462,EWR,BUF,56.0,282,22.0,21.0
822,2013,1,1,2224.0,24.0,2324.0,8.0,EV,N16561,4206,EWR,PWM,47.0,284,22.0,24.0
823,2013,1,1,2229.0,30.0,149.0,49.0,B6,N531JB,11,JFK,FLL,153.0,1069,22.0,29.0
824,2013,1,1,2240.0,-5.0,2340.0,-16.0,B6,N279JB,608,JFK,PWM,44.0,273,22.0,40.0
825,2013,1,1,2250.0,-5.0,2352.0,-7.0,B6,N521JB,1018,JFK,BOS,37.0,187,22.0,50.0
826,2013,1,1,2302.0,62.0,2342.0,49.0,EV,N13903,4276,EWR,BDL,24.0,116,23.0,2.0
827,2013,1,1,2306.0,21.0,28.0,23.0,B6,N281JB,30,JFK,ROC,59.0,264,23.0,6.0
828,2013,1,1,2307.0,22.0,32.0,35.0,B6,N178JB,128,JFK,BTV,59.0,266,23.0,7.0
829,2013,1,1,2310.0,15.0,24.0,9.0,B6,N646JB,112,JFK,BUF,57.0,301,23.0,10.0
830,2013,1,1,2312.0,192.0,21.0,191.0,EV,N13958,4312,EWR,DCA,44.0,199,23.0,12.0
831,2013,1,1,2323.0,83.0,22.0,69.0,EV,N13538,4257,EWR,BTV,44.0,266,23.0,23.0
832,2013,1,1,2326.0,116.0,131.0,73.0,B6,N594JB,199,JFK,LAS,290.0,2248,23.0,26.0
833,2013,1,1,2327.0,37.0,32.0,33.0,B6,N639JB,22,JFK,SYR,45.0,209,23.0,27.0
834,2013,1,1,2343.0,379.0,314.0,456.0,EV,N21197,4321,EWR,MCI,222.0,1092,23.0,43.0
835,2013,1,1,2353.0,-6.0,425.0,-20.0,B6,N591JB,739,JFK,PSE,195.0,1617,23.0,53.0
836,2013,1,1,2353.0,-6.0,418.0,-24.0,B6,N794JB,707,JFK,SJU,185.0,1598,23.0,53.0
837,2013,1,1,2356.0,-3.0,425.0,-12.0,B6,N588JB,727,JFK,BQN,186.0,1576,23.0,56.0
838,2013,1,1,NaN,NaN,NaN,NaN,EV,N18120,4308,EWR,RDU,NaN,416,NaN,NaN
839,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EHAA,791,LGA,DFW,NaN,1389,NaN,NaN
840,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EVAA,1925,LGA,MIA,NaN,1096,NaN,NaN
841,2013,1,1,NaN,NaN,NaN,NaN,B6,N618JB,125,JFK,FLL,NaN,1069,NaN,NaN

In [4]:
flights.iloc[2:9]

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
5,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0
6,2013,1,1,555.0,-5.0,913.0,19.0,B6,N516JB,507,EWR,FLL,158.0,1065,5.0,55.0
7,2013,1,1,557.0,-3.0,709.0,-14.0,EV,N829AS,5708,LGA,IAD,53.0,229,5.0,57.0
8,2013,1,1,557.0,-3.0,838.0,-8.0,B6,N593JB,79,JFK,MCO,140.0,944,5.0,57.0

In [5]:
flights.sort_values(['year', 'month', 'day'])
flights[['year', 'month', 'day']]

        year  month  day
0       2013      1    1
1       2013      1    1
2       2013      1    1
3       2013      1    1
4       2013      1    1
5       2013      1    1
6       2013      1    1
7       2013      1    1
8       2013      1    1
9       2013      1    1
10      2013      1    1
11      2013      1    1
12      2013      1    1
13      2013      1    1
14      2013      1    1
15      2013      1    1
16      2013      1    1
17      2013      1    1
18      2013      1    1
19      2013      1    1
20      2013      1    1
21      2013      1    1
22      2013      1    1
23      2013      1    1
24      2013      1    1
25      2013      1    1
26      2013      1    1
27      2013      1    1
28      2013      1    1
29      2013      1    1
...      ...    ...  ...
336746  2013      9   30
336747  2013      9   30
336748  2013      9   30
336749  2013      9   30
336750  2013      9   30
336751  2013      9   30
336752  2013      9   30
336753  2013      9   30
336754  2013      9   30
336755  2013      9   30
336756  2013      9   30
336757  2013      9   30
336758  2013      9   30
336759  2013      9   30
336760  2013      9   30
336761  2013      9   30
336762  2013      9   30
336763  2013      9   30
336764  2013      9   30
336765  2013      9   30
336766  2013      9   30
336767  2013      9   30
336768  2013      9   30
336769  2013      9   30
336770  2013      9   30
336771  2013      9   30
336772  2013      9   30
336773  2013      9   30
336774  2013      9   30
336775  2013      9   30

[336776 rows x 3 columns]

In [6]:
flights.tailnum.unique()
flights[['origin', 'dest']].drop_duplicates()

       origin dest
0         EWR  IAH
1         LGA  IAH
2         JFK  MIA
3         JFK  BQN
4         LGA  ATL
5         EWR  ORD
6         EWR  FLL
7         LGA  IAD
8         JFK  MCO
9         LGA  ORD
10        JFK  PBI
11        JFK  TPA
12        JFK  LAX
13        EWR  SFO
14        LGA  DFW
15        JFK  BOS
16        EWR  LAS
17        LGA  FLL
19        EWR  PBI
20        LGA  MSP
21        LGA  DTW
22        EWR  MIA
23        JFK  ATL
26        JFK  SFO
27        JFK  RSW
28        JFK  SJU
29        EWR  ATL
30        EWR  PHX
31        LGA  MIA
33        EWR  MSP
...       ...  ...
27377     JFK  ACK
27469     LGA  BGR
27477     LGA  MSN
27606     LGA  ORF
27696     JFK  IAH
27734     JFK  MCI
27738     LGA  OMA
27824     LGA  DSM
27857     LGA  GSP
27881     JFK  ABQ
27927     LGA  ILM
27955     LGA  SYR
29446     JFK  MVY
43734     LGA  SBN
57315     JFK  STL
77948     LGA  LEX
83558     EWR  SBN
100150    LGA  MHT
100631    LGA  CAE
101912    JFK  JAC
102295    JFK  SDF
137120    LGA  CHO
137696    JFK  MKE
177582    LGA  AVL
216127    JFK  BHM
235071    LGA  TVC
235826    LGA  MYR
254470    EWR  TVC
255455    EWR  ANC
275945    EWR  LGA

[224 rows x 2 columns]

In [7]:
flights['gain'] = flights.arr_delay - flights.dep_delay
flights['speed'] = flights.distance / flights.air_time * 60

In [8]:
flights.dep_delay.mean()

12.639070257304708

In [9]:
selection = np.random.choice(flights.index, 10)
flights.loc[selection]

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute,gain,speed
52725,2013,10,28,1650.0,-5.0,1812.0,-33.0,AA,N589AA,2223,LGA,STL,125.0,888,16.0,50.0,-28.0,426.240000
43803,2013,10,18,1920.0,40.0,2042.0,44.0,EV,N18557,4131,EWR,RIC,49.0,277,19.0,20.0,4.0,339.183673
201617,2013,5,9,1812.0,103.0,2106.0,99.0,B6,N703JB,985,LGA,TPA,141.0,1010,18.0,12.0,-4.0,429.787234
312920,2013,9,5,802.0,-8.0,1023.0,-37.0,UA,N16217,1218,EWR,DFW,174.0,1372,8.0,2.0,-29.0,473.103448
112279,2013,2,2,653.0,-6.0,947.0,-12.0,AA,N5FEAA,1815,JFK,MCO,144.0,944,6.0,53.0,-6.0,393.333333
154771,2013,3,20,1939.0,10.0,2151.0,-6.0,EV,N614QX,5181,EWR,ATL,109.0,746,19.0,39.0,-16.0,410.642202
232040,2013,6,11,1641.0,36.0,2001.0,50.0,UA,N75436,1556,EWR,SFO,360.0,2565,16.0,41.0,14.0,427.500000
9474,2013,1,11,1645.0,-10.0,1939.0,-50.0,DL,N336NB,706,JFK,AUS,212.0,1521,16.0,45.0,-40.0,430.471698
185202,2013,4,22,956.0,-4.0,1233.0,1.0,EV,N15574,4140,EWR,ATL,117.0,746,9.0,56.0,5.0,382.564103
33343,2013,10,7,2039.0,14.0,2347.0,5.0,DL,N3735D,2065,JFK,FLL,161.0,1069,20.0,39.0,-9.0,398.385093

In [10]:
planes = flights.groupby("tailnum")
delay = planes.agg({
    "year": "count",
    "distance": "median",
    "arr_delay": "mean"
})
delay.query("year > 20 & distance < 2000")

         year  distance  arr_delay
tailnum
N0EGMQ    371     719.0   9.982955
N10156    153     746.0  12.717241
N102UW     48     541.0   2.937500
N103US     46     529.0  -6.934783
N104UW     47     529.0   1.804348
N10575    289     533.0  20.691450
N105UW     45     529.0  -0.266667
N107US     41     541.0  -5.731707
N108UW     60     529.0  -1.250000
N109UW     48     535.0  -2.520833
N110UW     40     529.0   2.800000
N11106    129     746.0  14.880952
N11107    148     628.0  15.014388
N11109    148     638.0  14.851064
N11113    138     645.0  15.761905
N11119    148     708.0  30.306569
N11121    154     638.0  10.306122
N11127    124     746.0  13.605042
N11137    112     735.5  20.551402
N11140    157     708.0  18.312057
N11150    136     820.0   8.891473
N11155     98     746.0  12.989583
N11164    143     644.0  21.649635
N11165    159     746.0   8.346667
N11176    142     735.5  20.404580
N11181    125     642.0   9.075000
N11184    136     716.5   6.984375
N11187    133     645.0  11.190476
N11189    140     629.5   6.737226
N11191    136     708.0  21.935484
...       ...       ...        ...
N984DL     58     947.0   4.228070
N985AT     29     762.0  15.038462
N985DL     63     950.0   0.253968
N986AT     24     762.0   0.125000
N986DL     73    1020.0   5.583333
N987AT     28     762.0  37.384615
N987DL     55     950.0  -3.290909
N988AT     37     762.0  44.342857
N988DL     55     944.0   9.471698
N989AT     66     746.0  28.193548
N989DL     89     950.0  11.034091
N990AT     71     746.0  16.385714
N990DL     56     950.0  12.428571
N991AT     25     762.0  15.680000
N991DL     92    1007.5   7.336957
N992AT     38     762.0  17.783784
N992DL     57     950.0  -6.649123
N993AT     47     762.0  10.404255
N993DL     55     944.0  16.981132
N994AT     31     762.0  31.483871
N994DL     61     950.0   5.032787
N995DL     57     950.0   1.929825
N996AT     29     762.0   6.538462
N996DL    102     950.0   0.524752
N997AT     44     762.0  16.302326
N997DL     63     950.0   4.903226
N998AT     26     762.0  29.960000
N998DL     77     950.0  16.394737
N999DN     61    1020.0  14.311475
N9EAMQ    248     719.0   9.235294

[2873 rows x 3 columns]

In [11]:
daily = flights.groupby(['year', 'month', 'day'])
per_day = daily['distance'].count()
per_month = per_day.groupby(level=['year', 'month']).sum()
(
    flights.groupby(['year', 'month', 'day'])
    [['arr_delay', 'dep_delay']]
    .mean()
    .query('arr_delay > 30 | dep_delay > 30')
)

                arr_delay  dep_delay
year month day
2013 1     16   34.247362  24.612865
           31   32.602854  28.658363
     2     11   36.290094  39.073598
           27   31.252492  37.763274
     3     8    85.862155  83.536921
           18   41.291892  30.117960
     4     10   38.412311  33.023675
           12   36.048140  34.838428
           18   36.028481  34.915361
           19   47.911697  46.127828
           22   37.812166  30.642553
           25   33.681250  23.339564
     5     8    39.609183  43.217778
           23   61.970899  51.144720
           24   24.257415  30.340717
     6     2    26.075518  34.013366
           10   28.022293  30.619450
           13   63.753689  45.790828
           18   37.648026  35.950766
           24   51.176808  47.157418
           25   41.513684  43.063025
           26   27.317410  30.611752
           27   44.783296  40.891232
           28   44.976852  48.827784
           30   43.510278  44.188179
     7     1    58.280502  56.233825
           7    40.306378  36.617450
           8    29.648847  37.296646
           9    31.334365  30.711499
           10   59.626478  52.860702
           22   62.763403  46.667047
           23   44.959821  44.741685
           28   49.831776  37.710162
     8     1    35.989259  34.574034
           8    55.481163  43.349947
           9    43.313641  34.691898
           22   29.976744  33.600421
           28   35.203074  40.526894
     9     2    45.518430  53.029551
           12   58.912418  49.958750
     10    7    39.017260  39.146710
           11   18.922995  31.231838
     12    5    51.666255  52.327990
           8    36.911801  21.515337
           9    42.575556  34.800221
           10   44.508796  26.465494
           14   46.397504  28.361552
           17   55.871856  40.705602
           23   32.226042  32.254149